# This rule is not used by the project ebpfcontroller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ebpf.github.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ebpfcontroller
    app.kubernetes.io/managed-by: kustomize
  name: ebpfmap-admin-role
rules:
- apiGroups:
  - ebpf.github.com
  resources:
  - ebpfmaps
  verbs:
  - '*'
- apiGroups:
  - ebpf.github.com
  resources:
  - ebpfmaps/status
  verbs:
  - get
