---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ebpf.github.com
  resources:
  - ebpfmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ebpf.github.com
  resources:
  - ebpfmaps/finalizers
  verbs:
  - update
- apiGroups:
  - ebpf.github.com
  resources:
  - ebpfmaps/status
  verbs:
  - get
  - patch
  - update
