// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/ebpf_loader.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoadRequest contains the C source code to compile and load
type LoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceCode    string                 `protobuf:"bytes,1,opt,name=source_code,json=sourceCode,proto3" json:"source_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	mi := &file_proto_ebpf_loader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ebpf_loader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_proto_ebpf_loader_proto_rawDescGZIP(), []int{0}
}

func (x *LoadRequest) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

// LoadResponse contains the result of the loading operation
type LoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ProgramId     string                 `protobuf:"bytes,4,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"` // Identifier for the loaded program
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_proto_ebpf_loader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ebpf_loader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_proto_ebpf_loader_proto_rawDescGZIP(), []int{1}
}

func (x *LoadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LoadResponse) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

var File_proto_ebpf_loader_proto protoreflect.FileDescriptor

var file_proto_ebpf_loader_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x62, 0x70, 0x66, 0x5f, 0x6c, 0x6f, 0x61,
	0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x62, 0x70, 0x66, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x72, 0x22, 0x2e, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x77, 0x0a, 0x0c, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x32, 0x49,
	0x0a, 0x0a, 0x45, 0x62, 0x70, 0x66, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x04,
	0x4c, 0x6f, 0x61, 0x64, 0x12, 0x17, 0x2e, 0x65, 0x62, 0x70, 0x66, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x72, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x65, 0x62, 0x70, 0x66, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x61, 0x72, 0x73, 0x6c, 0x79, 0x72,
	0x69, 0x63, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x2f, 0x45, 0x42, 0x50, 0x46, 0x6f, 0x72, 0x67,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_ebpf_loader_proto_rawDescOnce sync.Once
	file_proto_ebpf_loader_proto_rawDescData []byte
)

func file_proto_ebpf_loader_proto_rawDescGZIP() []byte {
	file_proto_ebpf_loader_proto_rawDescOnce.Do(func() {
		file_proto_ebpf_loader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ebpf_loader_proto_rawDesc), len(file_proto_ebpf_loader_proto_rawDesc)))
	})
	return file_proto_ebpf_loader_proto_rawDescData
}

var file_proto_ebpf_loader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ebpf_loader_proto_goTypes = []any{
	(*LoadRequest)(nil),  // 0: ebpfloader.LoadRequest
	(*LoadResponse)(nil), // 1: ebpfloader.LoadResponse
}
var file_proto_ebpf_loader_proto_depIdxs = []int32{
	0, // 0: ebpfloader.EbpfLoader.Load:input_type -> ebpfloader.LoadRequest
	1, // 1: ebpfloader.EbpfLoader.Load:output_type -> ebpfloader.LoadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ebpf_loader_proto_init() }
func file_proto_ebpf_loader_proto_init() {
	if File_proto_ebpf_loader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ebpf_loader_proto_rawDesc), len(file_proto_ebpf_loader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ebpf_loader_proto_goTypes,
		DependencyIndexes: file_proto_ebpf_loader_proto_depIdxs,
		MessageInfos:      file_proto_ebpf_loader_proto_msgTypes,
	}.Build()
	File_proto_ebpf_loader_proto = out.File
	file_proto_ebpf_loader_proto_goTypes = nil
	file_proto_ebpf_loader_proto_depIdxs = nil
}
